version: '2'
services:
   proxy:
     build: ./nginx1
     container_name: proxy
     volumes:
       - /var/log/nginx:/var/log/nginx
     links:
         - web
     ports:
         - "8888:8888"
     tty: true
   web:
     container_name: web
     build: ./nginx2
#     depends_on:
#       - proxy
     tty: true
